#!/usr/bin/env python


from sys import *
import sys
from re import *

if len(argv)==2 and argv[1]=="-h":
  print "converts ucsc bed GENE extract to pip-acceptable feature-file"
  print "needs BLOCKS (whole gene models) as input."
  print " syntax: "
  print " cat test.bed | bed2pip"
  exit() 

#f = open(argv[1], 'r')

lines = stdin.readlines()

#convert lines
for line in lines:
     if line.startswith("track"):
	     continue
     if line.strip()=="":
       continue
     fields = line.split()
     bedstart = int(fields[1])
     if bedstart < 0:
         stderr.write("warning: replaced negative coordinates with 0\n")
         bedstart = 0
     bedend =  int(fields[2])
     name = "exon"
     strand = ""
     if (len(fields)>3):
         name = fields[3]
     if (len(fields)>4):
         strand = fields[5]
     if (len(fields)>8):
         blockStarts=fields[11].strip(",").split(",")
         blockSizes=fields[10].strip(",").split(",")
     if strand.strip() == "+":
       vistastrand="> "
     else: 
       if (strand.strip() == "-"):
           vistastrand="< "
       else:
           vistastrand=""

     print vistastrand+" ".join([str(bedstart)," ",str(bedend)," ",name])
     for start,size in zip(blockStarts,blockSizes):
         print bedstart+int(start), bedstart+int(start)+int(size)+1
