#!/usr/bin/env python


from sys import *
import sys
from re import *

if len(argv)==2 and argv[1]=="-h":
  print "converts ucsc bed GENE extract to vista-acceptable feature-file"
  print "will substract coordinates by startpos, if it is specified. Will truncate everthing "
  print "higher than endpos, if specified."
  print " OPTIONS:"
  print " -g: return as a gene-entry: prefixed by >"
  print " syntax: "
  print " cat test.bed | bed2vista <feature-type>"
  exit() 

allgene=0
for i in range(0,len(argv)):
    if argv[i]=="-g":
        allgene=1
        del argv[i]

if len(argv) > 1:
    name=argv[1]
    usebedname=0
else:
    usebedname=1

lines = stdin.readlines()

#convert lines
for line in lines:
     if line.startswith("track") or line.startswith("#") or line.startswith("browser"):
	     continue
     if line.strip()=="":
       continue

     fields = line.split()
     bedstart = int(fields[1])
     bedend =  int(fields[2])
     strand = ""
     if usebedname==1:
         if len(fields) < 4:
             stderr.write("no bedname found, please give a feature name to bed2vista\n")
             exit(1)
         name = fields[3]
     if (len(fields)>4):
         strand = fields[5]
     if not usebedname:
         vistastrand=""
     elif strand.strip() == "+" or allgene:
       vistastrand=">"
     else: 
       vistastrand="<"

     print vistastrand+" ".join([str(bedstart)," ",str(bedend)," ",name])
