#!/usr/bin/awk -f

BEGIN { FS = " "; 
        OFS = "\t"; }

$1 !~ /^#.*/      { 
                        strand = $5;
                        score = $6;
                        if (strand=="") 
                            { strand="."; }
                        if (score=="") 
                            { score="0.0"; }
                        frame=".";

                        # format: seq, progname, feat_type, start, stop, score, strand, frame(=".")
                    # HSFAU1        EMBL    exon    408     504     0.000   +       .       Sequence "HSFAU1.3" ; number 1
			print $1,"frombed",$4,$2,$3,score,strand,frame,"dummy";
		  }
