#!/usr/bin/env python

import logging, sys, optparse
from collections import defaultdict
from os.path import join, basename, dirname, isfile

# === COMMAND LINE INTERFACE, OPTIONS AND HELP ===
parser = optparse.OptionParser("usage: %prog [options] bigBedFname htmlDir - for each bed line, search for a file <name>.html in htmlDir and append it as a field to the bed file") 

parser.add_option("-d", "--debug", dest="debug", action="store_true", help="show debug messages") 
#parser.add_option("-f", "--file", dest="file", action="store", help="run on file") 
#parser.add_option("", "--test", dest="test", action="store_true", help="do something") 
(options, args) = parser.parse_args()

if options.debug:
    logging.basicConfig(level=logging.DEBUG)
else:
    logging.basicConfig(level=logging.INFO)
# ==== FUNCTIONs =====
    
# ----------- MAIN --------------
if args==[]:
    parser.print_help()
    exit(1)

filename = args[0]
htmlDir = args[1]

css = """
<style>
table { 
color: #333; /* Lighten up font color */
font-family: Helvetica, Arial, sans-serif; /* Nicer font */
width: 640px; 
border-collapse: 
collapse; border-spacing: 0; 
}

td, th { border: 1px solid #CCC; height: 30px; } /* Make cells a bit taller */

th {
background: #F3F3F3; /* Light grey background */
font-weight: bold; /* Make sure they're bold */
}

td {
text-align: left; 
}
</style>
""".replace("\n","").replace("\t"," ")

for line in open(filename):
    fields = line.rstrip("\n").split("\t")
    name = fields[3]
    #fname = join(htmlDir, name+".html")
    fname = join(htmlDir, name)
    if not isfile(fname):
        logging.warn("%s does not exist" % fname)
        html = ""
    else:
        html = open(fname).read().replace("\n","").replace("\t"," ")
    fields.append(css+html)
    print "\t".join(fields)


    
