#!/usr/bin/env python

import sys

if len(sys.argv)==1:
	print "convert data form nobel 05 paper to bed"
	print "syntax: chromatin2bed <filename>"
        sys.exit() 

f = open(sys.argv[1], "r")

for line in f:
	if line[0]=="#":
		continue
	parts = line.split()
	if parts[1]=="1":
		field1parts = parts[0].split("-")
		seq = field1parts[1]
		startpos = int(field1parts[2])
		endpos = startpos+225
		print seq.lower(), startpos, endpos

