#!/bin/csh -efx

unsetenv COPT

set TMPDIR = /scratch/tmp/max/
set cloneDir = $TMPDIR/kent
#chmod 775 $cloneDir
mkdir -p $TMPDIR

cd $TMPDIR
if ( -f $cloneDir/README ) then
   cd $cloneDir
   git pull
else
   git clone /cluster/home/max/kent/ $cloneDir
endif
pushd $cloneDir

cd src
make -j50 > /dev/null
make test > /dev/null
popd
#rm -rf $cloneDir
