#!/bin/bash
if [ "$1" == "-h" ]; then
echo "transform ensembl gff to bed (exons with gene names and strand)"
exit
fi

cut -f1,4,5,7,9 | gawk -F'\t' '{OFS="\t"; split($5,a,";"); split(a[1],gene,"\""); split(a[3],exon,"\""); print $1,$2,$3,gene[2] "_exon_"exon[2],"0",$4;}' | sed -e '/^[0-9]/s/^/chr/g'
