#!/usr/bin/env python


from sys import *
import sys
from re import *

def readfasta(lines):
  ## will read from lines
  ## will return a list of n seqs
  ## seq[n][0] is the seqname
  ## seq[n][1] is the sequence
  seqs = []
  for line in lines:
	  if line.startswith(">"):
	    seqs.append([line.strip(">").strip().split(" ")[0], ""])
	  else:
            #print seqs
            seqs[-1][1]+=line.strip().replace(" ","")
  return seqs



if len(argv)==2:
  print ""
  print "reads multi-fa sequence from stdin."
  print "print sequence names and sequence length to stdout"
  print " syntax: "
  print " seqlength <fastafile>"
  exit() 

lines = sys.stdin.readlines()
seqs = readfasta(lines)
del lines

for part in seqs:
        seq = part[1]
	name = part[0]
        print name, len(seq)
