#!/usr/bin/env python


from sys import *
import sys
from textwrap import *
import re

if len(argv)>1:
	print " will convert fasta file to vista alignment format."
        print " (=GLASS-format?)"
	print " EXAMPLE:"
	print " cat test.fa | fasta2vista"
        exit() 

lines = sys.stdin.readlines()

seqnames=[]
seqs=[]
seqcount = -1
#read in sequences and seqnames
for line in lines:
     # filter out newlines
     line = line.strip()
     if line=="":
       continue
      
     if line.startswith(">"):
       seqcount=seqcount+1
       seqs.append("")
       seqnames.append(line)
       continue

     #line has to be a sequence
     seqs[seqcount]=seqs[seqcount]+line.replace(" ","").strip()

del lines

#now we have the seqs in memory

aligncount = 0
for i in range(0, len(seqs[0])):
	if seqs[1][i]=="-":
		aligntype = " "
		alignedBase = "|"
		count = ""
	else:
		aligntype = "-"
		alignedBase = seqs[1][i]
		count = str(aligncount)
		aligncount += 1
	print i, seqs[0][i], aligntype, alignedBase, count
