#!/usr/bin/env python


from sys import *
import sys
from optparse import OptionParser
import Fasta
import tabfile

# === COMMAND LINE INTERFACE, OPTIONS AND HELP ===
parser = OptionParser("usage: %prog [options] idFile fastaFile - deletes all sequences where the first part of the id line occurs in a 2nd file") 

#parser.add_option("-l", "--minLen", dest="minLen", action="store", help="minimum sequence length, default %default", type="int", metavar="NUMBER", default="1") 
#parser.add_option("-m", "--maf", dest="maf", action="store_true", help="force maf format [default: %default]", default=True) 
#parser.add_option("-f", "--fasta", dest="maf", action="store_false", help="force fasta format (if not specified, we assume UCSC .maf file format") 
(options, args) = parser.parse_args()

# ----------- MAIN --------------
if len(args)==0:
    parser.print_help()
    exit() 

idFile = args[0]
infname = args[1]

ids = set(tabfile.slurplist(idFile))
seqs = Fasta.readFastaAsList(infname)

for s in seqs:
    seqid = s.id.split("|")[0]
    if not seqid in ids:
        #print s.toFasta(ranges=False)
        print ">"+s.id+"\n"+s.nucl+"\n"
