#!/usr/bin/env python

from sys import *
import sys
import re
from optparse import OptionParser

# === COMMAND LINE INTERFACE, OPTIONS AND HELP ===
parser = OptionParser("usage: %prog [options] fasta-file: reformat fasta header to apollo format") 
#parser.add_option("-s", "--substract", dest="substract", action="store_true", help="substract startpos instead of adding it", metavar="", default="False") 
#parser.add_option("-b", "--browser", dest="browser", action="store_true", help="add a 'browser position' line to the file", metavar="", default="False") 
#parser.add_option("-o", "--output", dest="stdout", action="store_true", help="do not overwrite file but write to stdout instead", metavar="", default="False") 

(options, args) = parser.parse_args()

#if len(args)==0:
#parser.print_help()
#exit() 
# -----------------

for l in sys.stdin:
    if l.startswith(">"):
        newl = l.replace("range=","").replace(":", " ").replace("-"," ")
        parts = newl.split()
        newl=parts[0]+" "+str(int(parts[2])-int((0.2*int(parts[2]))))+" "+str(int(parts[2])+int((0.2*int(parts[2]))))
        print newl
        continue
    else:
        print l

