#!/usr/bin/env python


from sys import *
import sys
from re import *

if len(argv)>=2:
	print "Remove Gaps ('-') from fasta file."
	print "Fasta File will be read from stdin."
        print "yes, I know this can be done with tr."
        print "but this is one of my first scripts, before I knew tr."
        print "I kept it for historical reaons. :-)"
        print " SYNTAX: "
        print " removeGaps"
        exit() 

lines = sys.stdin.readlines()

seqnames=[]
seqs=[]
seqcount = -1
#read in sequences and seqnames
for line in lines:
     # filter out newlines
     line = line.strip()
     if line=="":
       continue
      
     if line.startswith(">"):
       seqcount=seqcount+1
       seqs.append("")
       seqnames.append(line)
       continue

     #line has to be a sequence
     seqs[seqcount]=seqs[seqcount]+line.strip()


del lines
#now we have the seqs in memory
for i in range(0, len(seqs)):
	seqs[i] = seqs[i].replace("-","")
	seqs[i] = seqs[i].replace("N","")
  

for i in range(len(seqs)):
  print seqnames[i]
  print seqs[i]
