#!/usr/bin/python

import random
import sys
from popen2 import popen2
from optparse import OptionParser
import maxbio

# === COMMAND LINE INTERFACE, OPTIONS AND HELP ===
parser = OptionParser("usage: %prog [options] fastafile count: Choose any sequence at random from a multi-fasta file and return it. Optionally return a random part of a given length") 
parser.add_option("-l", "--length", dest="length", action="store", help="cut out a part of length x of the randomly choosen sequence", type="int", metavar="NUMBER", default="0") 
#parser.add_option("-r", "--repeat", dest="repeat", action="store", help="repeat x times", type="int", metavar="NUMBER", default="1") 
(options, args) = parser.parse_args()
if len(args)==0:
    parser.print_help()
    sys.exit(1)
# -----------------
fname, count = args
count = int(count)
# count sequences
#output, input = popen2("grep \> %s | wc -l " % fname )
#seqcount = int(output.readlines()[0])
seqs = list(maxbio.parseFasta(fname))
random.shuffle(seqs)

for seqId, seq in seqs[:count]:
    print ">"+seqId
    # print out this sequence or part of it
    if options.length==0:
        print seq
    else:
        rndstart = random.randrange(0,len(seq)-options.length-1)
        print "".join(seq[rndstart:rndstart+options.length])
