#!/usr/bin/env python

import sys

if len(sys.argv)==1:
	print ""
	print " Will extract a short piece of sequence from very big fasta files."
	print " (only one sequence per file)"
	print " All lines have to have equal length!"
	print " endpos can be higher than sequence length, we simply ouput spaces then."
	print " coord. are zero-based, half-open."
	print " Example:"
	print "  fastaextract ch01.fa 100000 100010 > test.fa"
	print ""
	print ""
        sys.exit() 

filename = sys.argv[1]
start = int(sys.argv[2])
end = int(sys.argv[3])-1

f = open(filename, "r")
line1 = f.readline()
print line1.strip(), "range="+str(start)+"-"+str(end)
savepos = f.tell()
line2 = f.readline()
f.seek(savepos)

# skip forward until line is reached
linelen = len(line2.strip())
lflen = len(line2) - len(line2.strip())
skiplines = start / linelen
f.seek(skiplines*(linelen+lflen),1)

# if there is only one line to read:
linesToRead = (end / linelen) - (start / linelen) 
startcol = start % linelen
endcol = end % linelen
if linesToRead==0:
	print f.readline()[startcol:endcol]
elif linesToRead==1:
	print f.readline()[startcol:].strip()
	print f.readline()[:endcol]
else:
	line = f.readline()
	print line[startcol:].strip()
	for i in range(linesToRead):
		print f.readline().strip()
	print f.readline()[:endcol]


