#!/usr/bin/env python


from sys import *
import sys

if len(argv)==1:
	print "format fasta file to x characters per line"
        print " SYNTAX: "
        print " wrapFasta <linelength>"
        exit() 

lines = sys.stdin.readlines()
size= int(argv[1])

seqnames=[]
seqs=[]
seqcount = -1
#read in sequences and seqnames
for line in lines:
     # filter out newlines
     line = line.strip()
     if line=="":
       continue
      
     if line.startswith(">"):
       seqcount=seqcount+1
       seqs.append("")
       seqnames.append(line)
       continue

     #line has to be a sequence
     seqs[seqcount]=seqs[seqcount]+line.replace(" ","").strip()

del lines

#now we have the seqs in memory

for i in range(len(seqs)):
  print seqnames[i]
  if len(seqs[i])>size:
	  last = 0
	  for l in range(size,len(seqs[i]),size):
		  print (seqs[i][last:l]).upper()
		  last = l
          print seqs[i][last:len(seqs[i])].upper()
  else:
	  print seqs[i].upper()
