#!/usr/bin/env python


from sys import *
import sys
import re

def readfasta(lines):
  ## will read from lines
  ## will return a list of n seqs
  ## seq[n][0] is the seqname
  ## seq[n][1] is the sequence
  seqs = []
  for line in lines:
	  if line.startswith(">"):
	    seqs.append([line.strip(">").split()[0], ""])
	  else:
            seqs[-1][1]+=line.replace(" ","").strip()
  return seqs

def revComp(seq):
	table = { "a" : "t", "A" : "T", "t" : "a", "T" : "A", "c" : "g", "C":"G", "g":"c", "G":"C", "-":"-" }
	newseq = ""
        for nucl in reversed(seq):
           newseq += table[nucl]
	return newseq


if len(argv)>1:
  print " Will create a matrix in Transfac matrix.dat-format."
  print " from a multi-fasta-file."
  print " Will read the fasta file from stdin."
  print
  print " syntax: "
  print " fasta2mat "
  exit() 

lines = sys.stdin.readlines()

seqs = readfasta(lines)
del lines
print "P0 A C G T "
i = 1

for pos in range(0, len(seqs[0][1])):
	print str(i)+" ",
	i += 1
	c = {'a':0, 'c':0,'t':0,'g':0,'-':0}
	for seq in seqs:
		c[seq[1][pos].lower()]+=1
	print c['a'],c['c'],c['g'],c['t']
	  
   
