#!/usr/bin/env python


from sys import *
import sys
from optparse import OptionParser
import Fasta

# === COMMAND LINE INTERFACE, OPTIONS AND HELP ===
parser = OptionParser("usage: %prog [options] filename - deletes all sequences where either the name or the sequence is empty") 

parser.add_option("-l", "--minLen", dest="minLen", action="store", help="minimum sequence length, default %default", type="int", metavar="NUMBER", default="1") 
#parser.add_option("-m", "--maf", dest="maf", action="store_true", help="force maf format [default: %default]", default=True) 
#parser.add_option("-f", "--fasta", dest="maf", action="store_false", help="force fasta format (if not specified, we assume UCSC .maf file format") 
(options, args) = parser.parse_args()

# ----------- MAIN --------------
if len(args)==0:
    parser.print_help()
    exit() 

infname = args[0]
minLen = options.minLen

seqs = Fasta.readFastaAsList(infname)

for s in seqs:
    if len(s.nucl)>= minLen:
        print s
