#!/usr/bin/awk -f

BEGIN { OFS = "\t"; }

$1 !~ /^#.*/ && $1 !~ /^track/ && $1 != ""    { 
			#split($9, a, "\""); 
			#print $1,$4,$5,a[6]"=factor="a[2]"_target="a[4]; 
                        if ($9=="") {
                                $9="NoN";
                            }
			print $1,$4,$5,$9,$6*1000,$7; 
		  }
