#!/usr/bin/env python

from sys import *
from optparse import OptionParser

# === COMMAND LINE INTERFACE, OPTIONS AND HELP ===
parser = OptionParser("usage: %prog [options] filename - count how often keys occur in hashfile") 

#parser.add_option("-l", "--wordlength", dest="motiflength", action="store", help="length of word [default: %default, hexamers]", type="int", metavar="NUMBER", default="6") 
#parser.add_option("-m", "--maf", dest="maf", action="store_true", help="force maf format [default: %default]", default=True) 
parser.add_option("-k", "--keepHeaders", dest="keepHeaders", action="store_true", help="keep first line of file") 
(options, args) = parser.parse_args()

# ==== FUNCTIONs =====
    
# ----------- MAIN --------------
if args==[]: 
    parser.print_help()
    exit(1)

data = {}
missingKey=0
if args[0]=="stdin":
    fh = stdin
else:
    fh = open(args[0])

if options.keepHeaders:
    headers = fh.readline()
else:
    headers = None

for l in fh:
    fs = l.strip().split("\t")
    if len(fs)!=2:
        missingKey+=1
        continue
    key, value = fs
    data.setdefault(key, 0)
    data[key]+=1

if headers:
    print headers,

for key, value in data.iteritems():
    print "%s\t%s" % (key, value)

stderr.write("info: lines with illegal format %d\n" % missingKey)
