#!/usr/bin/env python

import logging, sys, optparse
from collections import defaultdict
from os.path import join, basename, dirname, isfile

# === COMMAND LINE INTERFACE, OPTIONS AND HELP ===
parser = optparse.OptionParser("usage: %prog [options] - get a clean first sentence from the last tab-sep field, reads stdin, writes to stdout") 

parser.add_option("-d", "--debug", dest="debug", action="store_true", help="show debug messages") 
#parser.add_option("-f", "--file", dest="file", action="store", help="run on file") 
#parser.add_option("", "--test", dest="test", action="store_true", help="do something") 
(options, args) = parser.parse_args()

if options.debug:
    logging.basicConfig(level=logging.DEBUG)
else:
    logging.basicConfig(level=logging.INFO)
# ==== FUNCTIONs =====
    
# ----------- MAIN --------------
#if options.test:
    #logging.debug("test is set")
    #f = open(options.file, "r")
for line in sys.stdin:
    fields = line.rstrip("\n").split('\t')
    desc = fields[-1]
    sent = desc.split(". ")[0]
    fields[-1] = sent
    print "\t".join(fields)
