#!/usr/bin/env python

import logging, sys, optparse, socket
from collections import defaultdict
from os.path import join, basename, dirname, isfile

# === COMMAND LINE INTERFACE, OPTIONS AND HELP ===
parser = optparse.OptionParser("usage: %prog [options] - resolve IP to hostname") 

parser.add_option("-d", "--debug", dest="debug", action="store_true", help="show debug messages") 
#parser.add_option("-f", "--file", dest="file", action="store", help="run on file") 
#parser.add_option("", "--test", dest="test", action="store_true", help="do something") 
(options, args) = parser.parse_args()

if options.debug:
    logging.basicConfig(level=logging.DEBUG)
else:
    logging.basicConfig(level=logging.INFO)
# ==== FUNCTIONs =====
    
# ----------- MAIN --------------
if args!=[]:
    parser.print_help()
    exit(1)

for line in sys.stdin:
    ip = line.split()[0]
    try:
        host = socket.gethostbyaddr(ip)[0]
    except socket.herror:
        host = "unknown"

    print host+"\t"+line,
