#!/usr/bin/env python

import logging, sys, optparse
from os.path import basename

# === COMMAND LINE INTERFACE, OPTIONS AND HELP ===
parser = optparse.OptionParser("usage: %prog [options] filename - convert tab sep file to html table") 

parser.add_option("-d", "--debug", dest="debug", action="store_true", help="show debug messages") 
parser.add_option("-t", "--title", dest="title", action="store", help="title of table") 
parser.add_option("-s", "--subTitle", dest="subTitle", action="store", help="subTitle of table") 
#parser.add_option("-f", "--file", dest="file", action="store", help="run on file") 
#parser.add_option("", "--test", dest="test", action="store_true", help="do something") 
(options, args) = parser.parse_args()

if options.debug:
    logging.basicConfig(level=logging.DEBUG)
else:
    logging.basicConfig(level=logging.INFO)

# ==== FUNCTIONs =====
def main(args, options):
    if len(args)==0:
        inFname=None
    else:
        inFname = args[0]
    if inFname=="stdin" or inFname=="-" or inFname==None:
        inFh = sys.stdin
    else:
        inFh = open(inFname)

    # output headers
    headers = inFh.readline().strip("#").split("\t")
    htmlFh = sys.stdout
    #htmlFh = open(outHtml, "w")
    htmlFh.write("""<html><head>
    <style type="text/css">
    table { border-collapse:collapse; }
    td, th { border:1px solid black;padding:5px; }
    </style></head>
    """)

    title = basename(inFname).split(".")[0]
    if options.title:
        title = options.title

    rows = inFh.readlines()
    
    htmlFh.write("<body><h1>%s</h1><table>\n" % title)
    if options.subTitle:
        htmlFh.write("%s<p>\n" % options.subTitle)
    htmlFh.write("%d rows<p>" % len(rows))
    htmlFh.write("<tr><th>\n")
    htmlFh.write("</th><th>".join(headers))
    htmlFh.write("</th></tr>\n")

    for l in rows:
        row = l.rstrip("\n").split("\t")
        htmlFh.write("<tr>\n")
        for val in row:
            if ":" in val and "-" in val:
                htmlFh.write("""<td><a href="http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&position=%s">%s</a></td>""" % (val, val))
            else:
                htmlFh.write("<td>%s</td>" % val)
        htmlFh.write("</tr>\n")

    htmlFh.write("</table></body></html>\n")
    htmlFh.close()
                
    
# ----------- MAIN --------------
if args==[]:
    parser.print_help()
    exit(1)

main(args, options)
