#!/usr/bin/env python

import logging, sys, optparse
from collections import defaultdict
from os.path import join, basename, dirname, isfile

# === COMMAND LINE INTERFACE, OPTIONS AND HELP ===
parser = optparse.OptionParser("usage: %prog [options] - read 10 tab-sep lines from stdin and show them vertically") 

parser.add_option("-d", "--debug", dest="debug", action="store_true", help="show debug messages") 
#parser.add_option("-f", "--file", dest="file", action="store", help="run on file") 
#parser.add_option("", "--test", dest="test", action="store_true", help="do something") 
(options, args) = parser.parse_args()

if options.debug:
    logging.basicConfig(level=logging.DEBUG)
else:
    logging.basicConfig(level=logging.INFO)
# ==== FUNCTIONs =====
    
# ----------- MAIN --------------
#if args==[]:
    #parser.print_help()
    #exit(1)

i = 0
lines = []
for line in sys.stdin:
    fields = line.rstrip("\n").split("\t")
    for fi, f in enumerate(fields):
        if i==0:
            lines.append([f])
        else:
            lines[fi].append(f)
    i+=1
    if i>10:
        break

for l in lines:
    print "\t".join(l)
            

    
