test:
	bedOverlapOnlyLongest --joinBlocks test.bed test.out.bed
	cat test.out.bed

test2:
	bedOverlapOnlyLongest --joinBlocks testJoin.bed testJoin.out.bed
	cat testJoin.out.bed

test3:
	bedOverlapOnlyLongest testJoin.bed testJoin.out.bed
	cat testJoin.out.bed

e:
	vim ~/usr/src/scripts/bedOverlapOnlyLongest
