#!/usr/bin/env python

from sys import *
from optparse import OptionParser
import logging

# === COMMAND LINE INTERFACE, OPTIONS AND HELP ===
parser = OptionParser("usage: %prog [options] header1,header2,header3,... - read data from stdin and prefix it with headers") 
(options, args) = parser.parse_args()

if args==[]: 
    parser.print_help()
    exit(1)

headers = args[0]
line1 = "\t".join(headers.split(","))

print line1
print stdin.read(),
