#!/usr/bin/env python
import string
trTab = string.maketrans("\n\r\t", "   ")

import sys,csv
for row in csv.reader(sys.stdin):
    row = [r.strip().translate(trTab) for r in row]
    print "\t".join(row)
