#!/usr/bin/python
from optparse import OptionParser
import tabfile, os, shutil

parser = OptionParser("usage: %prog [options] table outDir") 
#parser.add_option("-f", "--fasta", dest="maf", action="store_false", help="force fasta format (if not specified, we assume UCSC .maf file format") 
(options, args) = parser.parse_args()

if args==[]: 
    parser.print_help()
    exit(1)

table = tabfile.slurpdict(args[0])
outDir=args[1]

for oldname, newname in table.iteritems():
    newPath = os.path.join(outDir, newname)
    print "old:", oldname, "new:", newPath
    if os.path.isfile(oldname):
        shutil.copy(oldname, newPath)
