#!/usr/bin/env python

import tabfile
from sys import *
from optparse import OptionParser
import os, popen2

# === COMMAND LINE INTERFACE, OPTIONS AND HELP ===
parser = OptionParser("usage: %prog [options] namazuSearch keywordfile outfile") 

#parser.add_option("-f", "--fasta", dest="maf", action="store_false", help="force fasta format (if not specified, we assume UCSC .maf file format") 
(options, args) = parser.parse_args()
infile, outfile = args

# MAIN

keywords = tabfile.slurplist(infile)
pmcIds = set()

for keyword in keywords:
    print keyword
    stdout, stdin = popen2.popen2('namazu --all --short "%s"' % keyword)
    # 360. PMC333532.txt (score: 38)
    for line in stdout:
        if "score" in line:
            fname = line.split()[1]
            pmcId = fname.strip(".txt.pdfPMC")
            pmcIds.add(pmcId)
    
of = open(outfile, "w")
for id in pmcIds:
    of.write(id+"\n")
of.close()
