#!/usr/bin/env python
from selenium import selenium
import unittest, time, re

PAGECOUNT = 331 # number of pages from JCR to download
OUTFILE = "jcr.html"

class Untitled2(unittest.TestCase):
    def setUp(self):
        self.verificationErrors = []
        self.selenium = selenium("localhost", 4444, "*chrome", "http://admin-apps.isiknowledge.com/")
        self.selenium.start()
    
    def test_untitled2(self):
        ofh = open(OUTFILE, "w")
        sel = self.selenium
        sel.open("http://admin.isiknowledge.com/SessionError.cgi?&DestApp=JCR&Error=No+SID+Received")
        sel.click("link=establish a new session")
        sel.wait_for_page_to_load("30000")
        sel.open("/JCR/JCR")
        sel.click("//input[@name='RQ' and @value='SELECT_ALL']")
        sel.click("Submit")
        sel.wait_for_page_to_load("30000")

        ofh.write(sel.get_html_source().encode("utf-8"))

        for i in range(0, 331):
            sel.click("//img[@alt='Next Page']")
            sel.wait_for_page_to_load("30000")
            ofh.write(sel.get_html_source().encode("utf-8"))
            time.sleep(1)
    
    def tearDown(self):
        self.selenium.stop()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()
