#!/usr/bin/python

from sys import *
from optparse import OptionParser
import tabfile

# === COMMAND LINE INTERFACE, OPTIONS AND HELP ===
parser = OptionParser("usage: %prog [options] sizes.lst fastafile") 

#parser.add_option("-l", "--wordlength", dest="motiflength", action="store", help="length of word [default: %default, hexamers]", type="int", metavar="NUMBER", default="6") 
#parser.add_option("-m", "--maf", dest="maf", action="store_true", help="force maf format [default: %default]", default=True) 
#parser.add_option("-f", "--fasta", dest="maf", action="store_false", help="force fasta format (if not specified, we assume UCSC .maf file format") 
(options, args) = parser.parse_args()

# ==== FUNCTIONs =====
    
# ----------- MAIN --------------
if args==[]: 
    parser.print_help()
    exit(1)

sizesfile = args[0]
sizes = tabfile.slurpdict(sizesfile)
fastafile = args[1]
f = open(fastafile, "r")

for l in f:
    if l.startswith(">"):
	chrom = l.strip().strip(">")
	size = sizes[chrom]
	print ">%s:1-%s" % (chrom, size)
    else:
	print l,
